version: "3"

set: [errexit, pipefail]

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  install:
    desc: Install dependencies
    cmds:
      - npm install

  build:
    desc: Build the package
    cmds:
      - npx tsup

  dev:
    desc: Build in watch mode
    cmds:
      - npx tsup --watch

  test:
    desc: Run tests
    cmds:
      - npx vitest run {{.CLI_ARGS}}

  test:watch:
    desc: Run tests in watch mode
    cmds:
      - npx vitest {{.CLI_ARGS}}

  lint:
    desc: Type-check with TypeScript
    cmds:
      - npx tsc --noEmit

  ci:
    desc: Run full CI pipeline (lint + test + build)
    cmds:
      - task: lint
      - task: test
      - task: build
